### ISSUE TITLE
监控kafka集群的问题

### ISSUE THREAD

**Issue by yy1** [shunfei/DCMonitor#34]
当前没有Active Topics启动会抛如下异常：
.671: [GC [PSYoungGen: 268361K->20976K(271872K)] 292396K->56096K(354816K), 0.0225720 secs] [Times: user=0.03 sys=0.00, real=0.02 secs] 
[2015-10-13 17:04:15.781] boot - 13404 ERROR [Thread-3] --- KafkaStats: 
java.lang.NullPointerException: null value in entry: topic=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135)
        at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:99)
        at com.sf.monitor.kafka.KafkaStats.createPoint(KafkaStats.java:100)
        at com.sf.monitor.kafka.KafkaStats.parsePartitionInfos(KafkaStats.java:80)
        at com.sf.monitor.kafka.KafkaStats.fetchStormKafkaPartitionInfos(KafkaStats.java:50)
        at com.sf.monitor.kafka.KafkaStats.fetchCurrentInfos(KafkaStats.java:25)
        at com.sf.monitor.kafka.KafkaInfoFetcher$1.run(KafkaInfoFetcher.java:41)

**Comment by flowbehappy** [comment]
Hi! You can try this commit, it should fix your exception. And plz let me known if it works, I will merge it. 
https://github.com/shunfei/DCMonitor/commit/90a310954a48828b38fed072a8cba07f4395dcc6 on brach `fix-issue34`

**Comment by yy1** [comment]
The code works.Thank you!

**Comment by yy1** [comment]
The code works.It's OK now.Thank you!

**Comment by flowbehappy** [comment]
@yy1 Glad to hear that!
