### ISSUE TITLE
监控storm消费kafka报异常

### ISSUE THREAD

**Issue by yy1** [shunfei/DCMonitor#39]
如果我配置错误的zkroot路径的情况下报如下异常：
015-10-20 16:26:08.573] boot - 2642  WARN [Thread-3] --- DCMZkUtils: read children of [/storm_kafka_comsumerx] from zookeeper failed!
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /storm_kafka_comsumerx
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1590)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:199)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38)
        at com.sf.monitor.utils.DCMZkUtils.getZKChildren(DCMZkUtils.java:72)
        at com.sf.monitor.kafka.KafkaInfos.getStormKafkaClients(KafkaInfos.java:348)
        at com.sf.monitor.kafka.KafkaStats.fetchStormKafkaPartitionInfos(KafkaStats.java:48)
        at com.sf.monitor.kafka.KafkaStats.fetchCurrentInfos(KafkaStats.java:25)
        at com.sf.monitor.kafka.KafkaInfoFetcher$1.run(KafkaInfoFetcher.java:41)
但是我的异常是这样的：
Oct 20, 2015 3:13:12 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException
        at com.sf.monitor.kafka.KafkaInfos.getStormKafkaClients(KafkaInfos.java:353)
        at com.sf.monitor.controllers.KafkaController.stormkafka(KafkaController.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1721)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1679)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
看到源代码发现已经读取到zkroot，报错的代码是KafkaInfos.java的第354行
![image](https://cloud.githubusercontent.com/assets/12421371/10602043/9d8b6688-7748-11e5-8e1a-e67b75c1df47.png)

**Comment by sundy-li** [comment]
You can try to pull a merge request, I will merge it.

**Comment by yy1** [comment]
第101行的异常抛到外面了
![image](https://cloud.githubusercontent.com/assets/12421371/10605220/6f379f2c-775c-11e5-8155-6c076d41e7e3.png)
request的值：Name: OffsetRequest; Version: 0; CorrelationId: 0; ClientId: ; ReplicaId: -1; RequestInfo: [collect,0] -> PartitionOffsetRequestInfo(-1,1)
就是这里导致的空值，到底如何改，我不会啊......

**Comment by sundy-li** [comment]
Try this commit  b1709b1 , plz let me know it works, I will merge it

**Comment by yy1** [comment]
It steal can't work.When I debug,I find these codes have some problems.
![image](https://cloud.githubusercontent.com/assets/12421371/10655891/9cb828b8-78ab-11e5-9ee2-8d6be21d5b17.png)

**Comment by sundy-li** [comment]
You just paste the exception, I will fix it

**Comment by yy1** [comment]
![image](https://cloud.githubusercontent.com/assets/12421371/10656371/8af03530-78b0-11e5-9df5-c19667055fd1.png)
![image](https://cloud.githubusercontent.com/assets/12421371/10656387/a28e5a28-78b0-11e5-9efa-d13fb5f5724e.png)

**Comment by sundy-li** [comment]
This is the reason caused by kafka, not the bug of Dcmonitor, plz check your kafka zookeeper environment.

**Comment by sundy-li** [comment]
This may be the kafka is not working right
