### ISSUE TITLE
"stormKafkaRoot": "/storm_kafka" error when i ran this project as it is

### ISSUE THREAD

**Issue by santhoo08** [shunfei/DCMonitor#45]
May be my question is silly, Im new to kafka, i;m trying to understand how it working. When i try to created the  /storm_kafka in standalone kafka running system and i'm running above specified steps but it is failing can you please help me to get rid of this issue. 

Can you able to provide the details what exactly i'm missing in configuration or running this project.

My configuration as below
i'm using kafka standalone :- kafka_2.12-2.0.0

cd /refresh/home/Software/kafka_2.12-2.0.0
bin/zookeeper-server-start.sh config/zookeeper.properties (Zookeeper default )
bin/kafka-server-start.sh config/server.properties (zookeeper.connect=localhost:2181/storm_kafka)
and created the /storm_kafka folder under root folder.

Topic creation:--
 bin/kafka-topics.sh --zookeeper localhost:2181/storm_kafka --create --topic Test1 --partitions 2 --replication-factor 1 

org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /consumers
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:685)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:413)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:409)
	at kafka.utils.ZkUtils$.getChildren(ZkUtils.scala:468)
	at kafka.utils.ZkUtils.getChildren(ZkUtils.scala)
	at com.sf.monitor.kafka.KafkaInfos.getActiveTopicMap(KafkaInfos.java:293)
	at com.sf.monitor.kafka.KafkaStats.fetchKafkaPartitionInfos(KafkaStats.java:32)
	at com.sf.monitor.kafka.KafkaStats.fetchCurrentInfos(KafkaStats.java:24)
	at com.sf.monitor.kafka.KafkaInfoFetcher$1.run(KafkaInfoFetcher.java:41)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /consumers
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1500)
	at org.I0Itec.zkclient.ZkConnection.getChildren(ZkConnection.java:99)
	at org.I0Itec.zkclient.ZkClient$2.call(ZkClient.java:416)
	at org.I0Itec.zkclient.ZkClient$2.call(ZkClient.java:413)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:675)
	... 8 more

**Comment by sundy-li** [comment]
Hi, it did not support kafka version above 0.8. And we had no plan to update this  repo in the future, maybe you could try some other repos... 

Sorry

**Comment by santhoo08** [comment]
Thanks for quick response.
I need to understand this ("stormKafkaRoot": "/storm_kafka") part. i stuck with this rest i can able to understand going through the code. 

I need help to get rid of this issue, Can you please let me know if I use 0.8 version that issue will resolve. how I can get rid of this /storm_kafka is there any specific configuration required for this.
Regards,P V Srinivas Rao 

    On Monday, August 6, 2018 7:43 AM, sundyli <notifications@github.com> wrote:
 

 Hi, it did not support kafka version above 0.8. And we had no plan to update this repo in the future, maybe you could try some other repos...Sorry—
